# Generated by Django 3.2 on 2022-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='friday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='lunch_hours',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='monday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='sunday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='thursday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='tuesday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='wednesday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='friday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='monday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='saturday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='sunday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='thursday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='tuesday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='wednesday',
            field=models.CharField(default='timezone.now', max_length=50),
        ),
    ]
