# Generated by Django 3.2 on 2022-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220227_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('background_image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
