# Generated by Django 3.2 on 2022-02-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name_plural': 'Dishes'},
        ),
    ]
