# Generated by Django 3.2 on 2022-03-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dishes_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='category',
            new_name='category_name',
        ),
    ]
